version: "3.8"
services:
    prod_box:
        container_name: prod
        build: .
        ports: 
            - "8888:8888"
            - "4040:4040"
        volumes: 
            - ./codebook:/home/jupyter/jupyter_default_dir
            - ./.aws:/root/.aws
        environment:
            - AWS_PROFILE=base_profile_prod
